#!/usr/bin/env python3
"""
BUILD NAV  ·  one data file drives the whole site's navigation.

    python3 tools/build_nav.py .

Master list:  _data/sitemap_nav.json
   { "Group name": [ ["page.html", "Label"], ... ], ... }

What this does with it:
  1. Rewrites the SECTIONS array inside mm-nav.js (between the AUTO markers)
     so the sticky top bar and its drawer match the master list.
  2. Adds <script src="mm-nav.js" defer></script> to every .html page that
     doesn't already have it, so the bar actually appears everywhere.

After this, adding a page to the site menu is one line in the JSON plus a
re-run. Nothing else needs editing. build_index.py reads the same JSON for
the Transmission Map, so the homepages stay in sync automatically.

Pages deliberately skipped (they are not menu items):
  google*.html            search-console verification stub
  index-*.html / index.html  generated homepages (template already has it)
  guestbook / rotary-line    removed from the site
"""
import json, re, sys, pathlib

REPO = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else '.')
DATA = REPO / '_data' / 'sitemap_nav.json'
NAV  = REPO / 'mm-nav.js'

SKIP_TAG = {'guestbook.html', 'rotary-line.html'}
SKIP_PREFIX = ('google',)

START = '  /* ==== AUTO:SECTIONS start — generated by tools/build_nav.py ==== */'
END   = '  /* ==== AUTO:SECTIONS end ==== */'


def js_str(s):
    """JS string literal, ASCII-safe so the file stays encoding-proof."""
    out = s.replace('\\', '\\\\').replace("'", "\\'")
    return "'" + ''.join(
        c if 32 <= ord(c) < 127 else '\\u%04x' % ord(c) for c in out) + "'"


def build_sections(nav):
    lines = [START, '  var SECTIONS = [']
    groups = list(nav.items())
    for gi, (group, items) in enumerate(groups):
        lines.append('    { name: %s, items: [' % js_str(group))
        for ii, (href, label) in enumerate(items):
            comma = '' if ii == len(items) - 1 else ','
            lines.append('      [%s, %s]%s' % (js_str(href), js_str(label), comma))
        lines.append('    ]}%s' % ('' if gi == len(groups) - 1 else ','))
    lines.append('  ];')
    lines.append(END)
    return '\n'.join(lines)


def main():
    nav = json.load(open(DATA, encoding='utf-8'))
    src = NAV.read_text(encoding='utf-8')

    # ---- 1. rewrite the SECTIONS block ----------------------------------
    block = build_sections(nav)
    if START in src and END in src:
        src = src[:src.index(START)] + block + src[src.index(END) + len(END):]
    else:
        # first run: replace the hand-written array
        m = re.search(r'  var SECTIONS = \[.*?\n  \];', src, re.S)
        if not m:
            sys.exit('could not find SECTIONS in mm-nav.js')
        src = src[:m.start()] + block + src[m.end():]
    NAV.write_text(src, encoding='utf-8')
    total = sum(len(v) for v in nav.values())
    print(f'mm-nav.js  ·  {len(nav)} groups, {total} links written from {DATA.name}')

    # ---- 2. make sure every page loads it -------------------------------
    TAG = '<script src="mm-nav.js?v=2" defer></script>'
    added, had, skipped = [], 0, []
    for page in sorted(REPO.glob('*.html')):
        name = page.name
        if name.startswith(SKIP_PREFIX) or name in SKIP_TAG:
            skipped.append(name); continue
        t = page.read_text(encoding='utf-8', errors='ignore')
        if 'mm-nav.js' in t:
            had += 1; continue
        if '</body>' not in t:
            skipped.append(name + ' (no </body>)'); continue
        i = t.rindex('</body>')
        page.write_text(t[:i] + TAG + '\n' + t[i:], encoding='utf-8')
        added.append(name)

    print(f'script tag ·  {had} already had it, {len(added)} added, {len(skipped)} skipped')
    if skipped:
        print('   skipped:', ', '.join(skipped))
    return added


if __name__ == '__main__':
    main()
