#!/usr/bin/env python3
"""
MAGICKMICA - build_pools.py
THE SIMPLE METHOD for the 16 index variants.

Before: every index page embedded its own 150-note MTV_NOTES blob and its
own hardcoded 8-card weekly grid. A refresh rewrote 16 large files.

After: the shared data lives in ONE file, pools.js. Each page loads it with
a plain <script src="pools.js"> before its own code, and the weekly grid is
rendered at runtime by mm-grid.js. Each page keeps its own design entirely.

  ONE-TIME:  python3 tools/build_pools.py --patch   (rewrites the 16 pages)
  EVERY RUN: python3 tools/build_pools.py           (rewrites pools.js only)

A plain script include is used rather than fetch() on purpose: it is
synchronous, so the page's existing code still finds MTV_NOTES exactly
where it expects it, with no async ordering problems and no CORS issues
when previewing from a local file.
"""
import json, os, re, glob, datetime

MAG_CDN = ("https://substackcdn.com/image/fetch/"
           "$s_!G4Yk!,w_400,c_limit,f_webp,q_auto:good,fl_progressive:steep/")


def week_cards(notes, n=8):
    weeks = {}
    for x in notes:
        d = datetime.date.fromisoformat(x["d"])
        wk = (d - datetime.timedelta(days=d.weekday())).isoformat()
        weeks.setdefault(wk, []).append(x)
    out = []
    for wk in sorted(weeks, reverse=True)[:n]:
        g = weeks[wk]
        s = datetime.date.fromisoformat(wk)
        e = s + datetime.timedelta(days=6)
        imgs = [x for x in g if x.get("t")]
        out.append({
            "href": f"week-{wk}.html",
            "cover": sorted(imgs, key=lambda x: -(x.get("l") or 0))[0]["t"] if imgs else "",
            "count": len(g),
            "label": f"{s.strftime('%b %-d')}\u2013{e.strftime('%b %-d')}",
        })
    return out


def mtv_pool(notes, old_tags=None, n=150):
    pool = sorted(notes, key=lambda x: (-(x.get("l") or 0), -int(x["id"])))[:n]
    out = []
    for x in pool:
        rec = {k: x[k] for k in ("d", "l", "r", "id", "b") if k in x}
        if old_tags and int(x["id"]) in old_tags:
            rec["c"] = old_tags[int(x["id"])]
        out.append(rec)
    return out


GRID_JS = """/* MAGICKMICA - renders the weekly Y3K grid from pools.js.
   Include after pools.js:  <script src="mm-grid.js" defer></script> */
(function () {
  function build() {
    var grid = document.querySelector('.mag-grid');
    if (!grid || typeof WEEK_CARDS === 'undefined') return;
    grid.innerHTML = WEEK_CARDS.map(function (c) {
      var img = c.cover
        ? '<img decoding="async" src="' + c.cover + '" loading="lazy" alt="' +
          c.label + ' weekly issue" ' +
          'onerror="this.parentElement.classList.add(\\'no-img\\')" />'
        : '';
      return '<a class="mag-card" href="' + c.href + '">' +
             '<div class="mag-card-cover">' + img +
             '<div class="mag-card-overlay"></div>' +
             '<div class="mag-card-count">' + c.count + ' NOTES</div></div>' +
             '<div class="mag-card-label">' + c.label + '</div></a>';
    }).join('');
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', build);
  } else { build(); }
})();
"""


def existing_tags(repo):
    """Carry forward the curated 'c' tags already on index.html."""
    p = os.path.join(repo, "index.html")
    if not os.path.exists(p):
        return {}
    h = open(p, encoding="utf-8").read()
    m = re.search(r"const MTV_NOTES = (\[.*?\]);", h, re.DOTALL)
    if not m:
        return {}
    try:
        return {int(x["id"]): x["c"] for x in json.loads(m.group(1)) if x.get("c")}
    except Exception:
        return {}


def write_pools(repo, out_dir, notes):
    tags = existing_tags(repo)
    payload = (
        "/* MAGICKMICA - shared data for index.html and every index-*.html.\n"
        "   Generated by tools/build_pools.py. Do not edit by hand. */\n"
        "const MTV_NOTES = " + json.dumps(mtv_pool(notes, tags),
                                          ensure_ascii=False, separators=(",", ":")) + ";\n"
        "const WEEK_CARDS = " + json.dumps(week_cards(notes),
                                           ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "pools.js"), "w", encoding="utf-8") as f:
        f.write(payload)
    with open(os.path.join(out_dir, "mm-grid.js"), "w", encoding="utf-8") as f:
        f.write(GRID_JS)
    return len(payload)


def patch_page(html_text):
    """One-time surgery: pull the inline blob out, empty the static grid,
    and load the shared files instead."""
    out = html_text
    changed = False

    # 1. inline MTV_NOTES -> external pools.js
    m = re.search(r"<script>\s*const MTV_NOTES = \[.*?\];", out, re.DOTALL)
    if m:
        out = (out[:m.start()]
               + '<script src="pools.js"></script>\n<script>'
               + out[m.end():])
        changed = True

    # 2. static mag-grid cards -> empty container, filled by mm-grid.js
    start = out.find('<div class="mag-grid">')
    if start != -1:
        depth, end = 0, None
        for mm in re.finditer(r"<div\b|</div>", out[start:start + 20000]):
            if mm.group(0) == "</div>":
                depth -= 1
                if depth == 0:
                    end = start + mm.end()
                    break
            else:
                depth += 1
        if end:
            out = out[:start] + '<div class="mag-grid"></div>' + out[end:]
            changed = True

    # 3. load the grid renderer
    if 'mm-grid.js' not in out:
        out = out.replace("</body>", '<script src="mm-grid.js" defer></script>\n</body>', 1)
        changed = True
    return out, changed


if __name__ == "__main__":
    import sys
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    repo = args[0] if args else "magickmica.github.io-main"
    data_dir = args[1] if len(args) > 1 else "_data"
    out_dir = args[2] if len(args) > 2 else "build"

    notes = json.load(open(os.path.join(data_dir, "notes_with_media_compact.json"),
                           encoding="utf-8"))
    size = write_pools(repo, out_dir, notes)
    print(f"pools.js written ({size:,} bytes) + mm-grid.js")

    if "--patch" in sys.argv:
        n = 0
        for f in ["index.html"] + sorted(glob.glob(os.path.join(repo, "index-*.html"))):
            name = os.path.basename(f)
            src = os.path.join(out_dir, name)
            if not os.path.exists(src):
                src = os.path.join(repo, name)
            if not os.path.exists(src):
                continue
            text = open(src, encoding="utf-8").read()
            new, ch = patch_page(text)
            if ch:
                open(os.path.join(out_dir, name), "w", encoding="utf-8").write(new)
                n += 1
        print(f"patched {n} index pages to use the shared files")
